version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./docker/web/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/web/ssl:/etc/ssl/private
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=database
      - DB_NAME=risolviamosubito
      - DB_USER=risolviamosubito_user
      - DB_PASS=risolviamosubito_pass_2025
      - REDIS_HOST=redis
    depends_on:
      - database
      - redis
    networks:
      - app-network

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: risolviamosubito_root_2025
      MYSQL_DATABASE: risolviamosubito
      MYSQL_USER: risolviamosubito_user
      MYSQL_PASSWORD: risolviamosubito_pass_2025
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=database
      - PMA_USER=risolviamosubito_user
      - PMA_PASSWORD=risolviamosubito_pass_2025
    depends_on:
      - database
    networks:
      - app-network

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge